// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate needs the direct (non-pooled) connection; the pooled DATABASE_URL
    // is used by the app at runtime via the driver adapter in lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
